### ISSUE TITLE
Assembly and Breakpoint layouts fail to show

### ISSUE THREAD

**Issue by srvasn** [cyrus-and/gdb-dashboard#163]
![Bug](https://user-images.githubusercontent.com/12023996/65754609-0976bd80-e12f-11e9-829c-339572376fd3.png)

Encountered this while debugging an android application through gdbserver.
Target application architecture - ARM 32 bit.
GDB used - gdb-multiarch  7.11.1
GDBServer used - 7.11

Assembly can be viewed normally using `layout asm`.

**Comment by cyrus-and** [comment]
That's weird, it behaves as if it were an older GDB version where `pending` was not defined... are you sure about the versions?

**Comment by srvasn** [comment]
```
➜  ~ gdb-multiarch --version
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
```

I'm not sure how to check if the Python bindings are up to date.

**Comment by cyrus-and** [comment]
Try these and tell me if you face the same problem:

- start the server locally instead of on Android and attach to it;

- debug locally without the server.

**Comment by srvasn** [comment]
Yes, both scenarios result in the same outcome.

**Comment by cyrus-and** [comment]
Alright I can reproduce that with Ubuntu 16, let me fix...

**Comment by cyrus-and** [comment]
It should be fixed now, thanks for reporting!

**Comment by srvasn** [comment]
![Screenshot from 2019-09-27 21-04-39](https://user-images.githubusercontent.com/12023996/65782156-aefb5280-e16a-11e9-8de3-7df3041df99a.png)

Tried using the latest version from master to come across this.

**Comment by cyrus-and** [comment]
Ah... yet another change in the API, it should be fixed now.

**Comment by srvasn** [comment]
@cyrus-and I can confirm that https://github.com/cyrus-and/gdb-dashboard/commit/462b7d658db08655bc8e80a5b6435e4a93554a51 does not fix this for me. Still the same error.

**Comment by cyrus-and** [comment]
https://github.com/cyrus-and/gdb-dashboard/blob/462b7d658db08655bc8e80a5b6435e4a93554a51/.gdbinit#L312

Now this is really weird, `gdb.breakpoints()` returns `None` instead of `[]` in your version so that `or` should fix this.

```
>>> python print(gdb.breakpoints())
None
>>> python print(gdb.breakpoints() or [])
[]
```

**Comment by srvasn** [comment]
@cyrus-and Looks like I botched up the patching operation. It works now ! Thanks for the awesome work and prompt responses !

**Comment by cyrus-and** [comment]
Oh, great! :) You're welcome.
